---
# Usage:
#   ANSIBLE_CONFIG=./ansible.cfg ansible-playbook playbooks/full_rke2_config.yml
#   ANSIBLE_CONFIG=./ansible.cfg ansible-playbook playbooks/full_rke2_config.yml --tags display_variables
#   ANSIBLE_CONFIG=./ansible.cfg ansible-playbook playbooks/full_rke2_config.yml --tags prerequisites
#   ANSIBLE_CONFIG=./ansible.cfg ansible-playbook playbooks/full_rke2_config.yml --tags server
#   ANSIBLE_CONFIG=./ansible.cfg ansible-playbook playbooks/full_rke2_config.yml --tags agent

- name: Display nodes info
  hosts: all
  gather_facts: true
  tags: [display_variables, always]
  tasks:
    # =====================================================
    # Display information
    # =====================================================
    - name: Show hostname details
      debug:
        msg: |
          ============================================
          HOST: {{ inventory_hostname }}
          ============================================
          Inventory Hostname: {{ inventory_hostname }}
          Ansible User: {{ ansible_user }}
          Ansible Hostname: {{ ansible_hostname }}
          Primary IP: {{ ansible_host }}
          Hostname Override: {{ hostname_override | default('N/A') }}
          Group Membership: {{ group_names | join(', ') }}

- name: Prepare all nodes
  hosts: all
  become: true
  gather_facts: true
  tags: [prerequisites]
  roles:
    - role: prerequisites

- name: Install RKE2 Control Planes
  hosts: control_planes
  become: true
  gather_facts: true
  tags: [server]
  roles:
    - role: rke2_server

- name: Install RKE2 Workers
  hosts: workers
  become: true
  gather_facts: true
  tags: [agent]
  serial: 1
  roles:
    - role: rke2_agent
